
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rinopvelrutxdukjwjkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpbm9wdmVscnV0eGR1a2p3amtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDg3MzYsImV4cCI6MjA1NzQyNDczNn0.bZQfwJxC1jUule43TjJ-XgTsr17TKtQB1sx34p2SryY";

// Create Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Initialize channel for realtime updates
export const jobApplicationsChannel = supabase.channel('job_applications_channel');
